blank_issues_enabled: true
contact_links:
  - name: Questions or Discussions
    url: https://github.com/Aravindraj-R/hello-worldnew/discussions
    about: Ask questions or start discussions about the project
